### ISSUE TITLE
add question links

### ISSUE THREAD

**Issue by rsharifnasab** [amirhosseinNouri/code-wars#1]
please consider adding a link to the questions, near your submission. for example I really don't know [this solutions](https://github.com/amirhosseinNouri/code-wars/tree/master/isSquare) are solving which problem. :)

**Comment by rsharifnasab** [comment]
same thing applies for [learning repo](https://github.com/amirhosseinNouri/Learning/tree/master/leet-code/twoSum) too.

**Comment by amirhosseinNouri** [comment]
@rsharifnasab Thanks for your great advice. I'll add the links for the next challenges. Although, Codewar challenges are available in each directory's README (with examples :D).
